# Generated by Django 6.0.2 on 2026-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_estimated_delivery_order_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Packed', 'Packed'), ('On the Way', 'On the Way')], default='Pending', max_length=20),
        ),
    ]
