# Generated by Django 6.0.2 on 2026-02-14 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_pincode_order_shipping_address_order_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_brand',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
